# -*- coding: utf-8 -*-
"""CIFAR10_Transfer_Learning_with_ViT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unaoHdP7gk5is6Ra7BlPgJf1V97AhCyf
"""

from torchvision import transforms

import __future__
from __future__ import print_function

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from PIL import Image
import matplotlib.pyplot as plt

import torchvision.transforms as transforms
import torchvision.models as models

import os
import imageio
import torchvision
from torch.utils.data import Dataset
from torchvision.datasets import CIFAR10
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import f1_score, confusion_matrix

torch_device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Using device:", torch_device)

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)

else:
    print("No GPU detected")

raw_data_train = '/content/drive/MyDrive/Machine Learning/Datasets/CIFAR-10-images-master/train'

raw_data_test = '/content/drive/MyDrive/Machine Learning/Datasets/CIFAR-10-images-master/train'

PATH = "/content/drive/MyDrive/"

lr = 1e-4
BATCH_SIZE = 64
N_EPOCHS = 10
NUM_CLASSES = 10

# Preprocessing
train_preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(224, padding=16),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

train_dataset = CIFAR10(root='./data', train=True,  download=True, transform=train_preprocess)

test_dataset  = CIFAR10(root='./data', train=False, download=True, transform=eval_preprocess)

print(f"Train size: {len(train_dataset)}")
print(f"Test size:  {len(test_dataset)}")

# Dataloaders
train_dl = torch.utils.data.DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

test_dl = torch.utils.data.DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Model (Visual Transformer)
model = models.vit_b_32(weights=models.ViT_B_32_Weights.DEFAULT)

model.heads = torch.nn.Linear(
    in_features=model.heads.head.in_features,
    out_features=NUM_CLASSES
)

torch.nn.init.xavier_uniform_(model.heads.weight)
print(model)


model.train()

# Loss + Adam Optimizer
loss_fn = nn.CrossEntropyLoss(label_smoothing=0.1) # Label Smoothing to prevent overconfidence

params = [param for name, param in model.named_parameters() if 'heads' not in str(name)]

opt = torch.optim.Adam(
    [{'params': params}, {'params': model.heads.parameters(), 'lr': lr*10}],
    lr=lr
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=N_EPOCHS)

def training_loop(N_EPOCHS, model, loss_fn, opt, scheduler):

  best_f1 = 0.0

  for epoch in range(N_EPOCHS):
    model.train()

    for xb, yb in train_dl:
      xb = xb.to(torch_device)
      yb = yb.to(torch_device)

      y_pred = model(xb)
      loss = loss_fn(y_pred, yb)

      opt.zero_grad()
      loss.backward()
      opt.step()

    scheduler.step()

    # End of Epoch Evaluation
    model.eval()

    all_preds, all_targets = [], []

    with torch.no_grad():
      for xb, yb in test_dl:
        xb = xb.to(torch_device)
        yb = yb.to(torch_device)
        preds = torch.argmax(model(xb), dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(yb.cpu().numpy())

    epoch_f1 = f1_score(all_targets, all_preds, average='macro')

    if epoch > best_f1:
      best_f1 = epoch_f1
      torch.save(model.state_dict(), PATH + "best_weights.pt")

    print(f"Epoch: {epoch}\n Loss: {loss.item():.4f}\n Epoch F1: {epoch_f1:.4f} ")

  print(f"Best F1 Score: {best_f1:.4f}")

model.to(torch_device)

params = [param for name, param in model.named_parameters() if 'heads' not in str(name)]

opt = torch.optim.Adam([
    {'params': params}, {'params': model.heads.parameters(), 'lr': lr*10}],lr=lr
  )

training_loop(N_EPOCHS, model, loss_fn, opt, scheduler)

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

# Single Image Prediction
model.eval()

def predict_image(img_path):
  img = imageio.imread(img_path)

  transform = transforms.Compose([
      transforms.ToPILImage(),
      transforms.Resize((224,224)),
      transforms.ToTensor(),

      transforms.Normalize(mean=[0.485, 0.456, 0.406],
                  std=[0.229, 0.224, 0.225])
      ])

  img = transform(img).unsqueeze(0).to(torch_device)

  with torch.no_grad():
    out = model(img)
    pred = torch.argmax(out, dim=1).item()

  return class_names[pred]

model.load_state_dict(torch.load(PATH + "best_weights.pt"))

model.eval()

all_preds = []
all_targets = []

with torch.no_grad():
  for xb, yb in test_dl:
    xb = xb.to(torch_device)
    yb = yb.to(torch_device)

    out = model(xb)
    preds = torch.argmax(out, dim=1)

    all_preds.extend(preds.cpu().numpy())
    all_targets.extend(yb.cpu().numpy())

f1 = f1_score(all_targets, all_preds, average='macro')
print(f"F1-Score: ", f1)

cm = confusion_matrix(all_targets, all_preds)
print("Confusion Matrix:\n", cm)

plt.imshow(cm)
plt.colorbar()
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show

